### ISSUE TITLE
Update descriere CivicTech Ro

### ISSUE THREAD

**Issue by LigiaAdam** [civictechro/guidelines#15]
#### CE? -> De inlocuit:
CivicTech România își dorește să folosească potențialul tehnologiei Open Source și talentul specialiștilor români pentru a dezvolta noi servicii digitale de utilitate publică.

#### CU

CivicTech Romania este comunitatea celor care lucrează împreună ca să modernizeze România, folosind potențialul tehnologiei deschise (Open Source) și talentul specialiștilor din IT&C pentru a dezvolta noua generație de servicii digitale de utilitate publică din România. Mai multe detalii despre proiectele CivicTech România pe https://civictech.ro/.

#### UNDE:
primul paragraf din https://civictechro.github.io/guidelines/ 

#### Alte specificari:
de avut in vedere inlocuirea pe unde mai apare

**Comment by ClaudiuCeia** [comment]
Fixed - acum repar si pe playbook (ala nu e public inca - deci daca sunt modificari mai mari, now is the time, https://github.com/civictechro/playbook/)
